### ISSUE TITLE
Rapid text entry, clicking around leads to no reaction on input or clicks

### ISSUE THREAD

**Issue by manifestarium** [ngrx/example-app#24] opened 2016-07-24 21:25 UTC
This happens in desktop chrome and on android chrome - any ideas?

**Comment by krjordan** [comment] 2016-07-26 15:24
I'm unable to reproduce, can you be more specific with what steps you took?

**Comment by MikeRyan52** [comment] 2016-08-09 00:40
Closing this for now. @manifestarium feel free to re-open if you can get us steps to reproduce!

**Closed by MikeRyan52** 2016-08-09 00:40 UTC
