### ISSUE TITLE
npm start run fails - index has no exported member 'ModuleWithProviders'

### ISSUE THREAD

**Issue by billsworld** [ngrx/example-app#44] opened 2016-09-15 03:51 UTC
I followed the quickstart instructions but ```npm start run``` fails with the following message

```
[default] /Project/ngrx-example/node_modules/@ngrx/store/ng2.d.ts:5:23
    Module '"/Project/ngrx-example/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'
```

**Comment by billsworld** [comment] 2016-09-20 03:17
I tried the rc5 branch and get another error
![error](https://cloud.githubusercontent.com/assets/16911647/18656447/2b16b240-7ebf-11e6-8f9a-fdd08a01fff0.jpg)

**Comment by billsworld** [comment] 2016-09-21 03:50
@MikeRyan52 let me know that this could be caused by an older version of node. I updated to the latest and now I am seeing this 
![2__webpack-dashboard__node_](https://cloud.githubusercontent.com/assets/16911647/18697205/12efd844-7f8d-11e6-96d6-81c05a58eb77.jpg)

**Comment by billsworld** [comment] 2016-09-22 01:28
it looks like that webpack issue was a quick bug in the latest beta. I updated modules and now getting ```Module '"/Users/mike/ngrx-example/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'.```

**Comment by krjordan** [comment] 2016-10-03 21:46
Duplicate of #33. I'm unable to reproduce after upgrading to Angular 2 final. If you're still having this issue, I would recommend upgrading to Angular 2 final or trying the steps listed in #33.

**Closed by krjordan** 2016-10-03 21:46 UTC
