### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by marklagendijk** [ngrx/example-app#99] opened 2017-01-09 15:46 UTC
It would be great if we have unit tests with 100% coverage, so people can also learn how to test all the ngrx stuff.

**Comment by vespertilian** [comment] 2017-01-26 14:26
Here are some sample test's I hope to get merged in, pending a style review. 

https://github.com/vespertilian/example-app/blob/master/src/app/effects/collection.spec.ts
https://github.com/vespertilian/example-app/blob/master/src/app/reducers/book.spec.ts

**Comment by krjordan** [comment] 2017-02-10 19:34
Duplicate of #45

**Closed by krjordan** 2017-02-10 19:34 UTC
